In [2]:
import pandas as pd

In [3]:
hmh = pd.read_excel('./data/긍정_허무함.xlsx')
sc = pd.read_excel('./data/긍정_상처.xlsx')
dh = pd.read_excel('./data/긍정_당황.xlsx')
happy = pd.read_excel('./data/행복증강.xlsx')

In [35]:
aug = pd.concat([hmh, sc, dh, happy], axis=0)
aug = aug.reset_index(drop=True)
aug

                                                   word emotion  emo_num
0     이 짧은 문장을 읽고 그날 하루종일...전..27년이라는제 인생을 잠시 돌아봤답니다...     허무함       13
1       이 문장을 읽고 하루종일...전..27년이라는제 인생을 잠시 돌아봤답니다....^^a     허무함       13
2     이 짧은 문장을 읽고 그날 하루종일...전..27년이라는제 인생을 돌아봤답니다......     허무함       13
3     이 짧은 문장을 읽고 그날 하루종일...전..27년이라는제 잠시 돌아봤답니다....^^a     허무함       13
4     이 이 짧은 문장을 읽고 그날 하루종일...전..27년이라는제 인생을 잠시 돌아봤답...     허무함       13
...                                                 ...     ...      ...
1371                     대신에 시 시험 끝나면 얼마든지 귀여워해 줘도 된단다.      행복        2
1372                           열심히 저 네! 할게요! 형님, 감사합니다!      행복        2
1373                           네! 형님, 열심히 할게요! 저 감사합니다!      행복        2
1374                           네! 감사합니다! 열심히 할게요! 형님, 저      행복        2
1375                           네! 저 열심히 할게요! 형님, 감사합니다!      행복        2

[1376 rows x 3 columns]

In [36]:
df = pd.read_excel('./data/긍정일상문.xlsx')
df

                                                   word emotion  emo_num
0                                    유재석 오라버니 해피투게더 봤어요      흥미        5
1                   우리모두 준혁이성과 LG선수들이 선전할수 있게 기를 넣어줍시다.      기쁨        1
2                                        웃긴거 알죠?~ㅋㅋㅇ ㅏ~      기쁨        1
3                                덕분에 주방에서 요리하는게 넘 좋아졌어요      감사        3
4            마지막 순간 손가락으로 총을 만들어 쏘실때에는 제가 직접 맞는 것 같습니다.      감사        3
...                                                 ...     ...      ...
7034                                  봐봐, 이거 너무 복실복실하지?      편안        0
7035  하긴 남자애니까. 별로 관심 없으려나? 그래도 여기 남성 의류 말야, 평판이 꽤 좋...      만족        4
7036                  이럴 땐 진짜 질색하는 표정이 된다니깐. 감탄스럽기까지 해.      불만       17
7037  너무 대놓고 그러면 역효과잖니? 난 지금 이대로면 충분한걸. ……하긴, 옛날엔 페어...      만족        4
7038       고맙긴요. 제가 할 수 있는 건 이 정도가 전부인걸요. 선배님, 부디 힘내세요.      걱정       16

[7039 rows x 3 columns]

In [37]:
DF = pd.concat([df,aug], axis=0)
DF = DF.reset_index(drop=True)
DF

                                              word emotion  emo_num
0                               유재석 오라버니 해피투게더 봤어요      흥미        5
1              우리모두 준혁이성과 LG선수들이 선전할수 있게 기를 넣어줍시다.      기쁨        1
2                                   웃긴거 알죠?~ㅋㅋㅇ ㅏ~      기쁨        1
3                           덕분에 주방에서 요리하는게 넘 좋아졌어요      감사        3
4       마지막 순간 손가락으로 총을 만들어 쏘실때에는 제가 직접 맞는 것 같습니다.      감사        3
...                                            ...     ...      ...
8410                대신에 시 시험 끝나면 얼마든지 귀여워해 줘도 된단다.      행복        2
8411                      열심히 저 네! 할게요! 형님, 감사합니다!      행복        2
8412                      네! 형님, 열심히 할게요! 저 감사합니다!      행복        2
8413                      네! 감사합니다! 열심히 할게요! 형님, 저      행복        2
8414                      네! 저 열심히 할게요! 형님, 감사합니다!      행복        2

[8415 rows x 3 columns]

In [38]:
DF = DF.drop_duplicates(['word'], keep='first')
DF = DF.reset_index(drop=True)
DF

                                              word emotion  emo_num
0                               유재석 오라버니 해피투게더 봤어요      흥미        5
1              우리모두 준혁이성과 LG선수들이 선전할수 있게 기를 넣어줍시다.      기쁨        1
2                                   웃긴거 알죠?~ㅋㅋㅇ ㅏ~      기쁨        1
3                           덕분에 주방에서 요리하는게 넘 좋아졌어요      감사        3
4       마지막 순간 손가락으로 총을 만들어 쏘실때에는 제가 직접 맞는 것 같습니다.      감사        3
...                                            ...     ...      ...
8054                     대신에 끝나면 얼마든지 귀여워해 줘도 된단다.      행복        2
8055                대신에 시 시험 끝나면 얼마든지 귀여워해 줘도 된단다.      행복        2
8056                      열심히 저 네! 할게요! 형님, 감사합니다!      행복        2
8057                      네! 형님, 열심히 할게요! 저 감사합니다!      행복        2
8058                      네! 감사합니다! 열심히 할게요! 형님, 저      행복        2

[8059 rows x 3 columns]

In [11]:
DF.to_excel('./data/긍정일상문_증강.xlsx', index=False)

In [39]:
dic = pd.read_excel('./data/최종사전_증강(부정).xlsx')
dic

                       word emotion  emo_num
0                 가능성이 늘어나다      만족        4
1                  가능성이 있다고      기쁨        1
2                      가능하다      편안        0
3                  가볍고 상쾌하다      기쁨        1
4                   가볍고 상쾌한      기쁨        1
...                     ...     ...      ...
27834             내글 배 당했다.      당황        8
27835            내글 당했다. 삭제      당황        8
27836  설마 이짓할줄예상은했는데 근데진짜한다      당황        8
27837  근데진짜한다 설마 이짓할줄예상은했는데      당황        8
27838       친일파일줄이야... 티파니가      당황        8

[27839 rows x 3 columns]

In [44]:
fdic = pd.concat([dic,DF], axis=0)
fdic = fdic.reset_index(drop=True)
fdic

                                 word emotion  emo_num
0                           가능성이 늘어나다      만족        4
1                            가능성이 있다고      기쁨        1
2                                가능하다      편안        0
3                            가볍고 상쾌하다      기쁨        1
4                             가볍고 상쾌한      기쁨        1
...                               ...     ...      ...
35893       대신에 끝나면 얼마든지 귀여워해 줘도 된단다.      행복        2
35894  대신에 시 시험 끝나면 얼마든지 귀여워해 줘도 된단다.      행복        2
35895        열심히 저 네! 할게요! 형님, 감사합니다!      행복        2
35896        네! 형님, 열심히 할게요! 저 감사합니다!      행복        2
35897        네! 감사합니다! 열심히 할게요! 형님, 저      행복        2

[35898 rows x 3 columns]

In [45]:
fdic = fdic.drop_duplicates(['word'], keep='first')
fdic = fdic.reset_index(drop=True)
fdic

                                 word emotion  emo_num
0                           가능성이 늘어나다      만족        4
1                            가능성이 있다고      기쁨        1
2                                가능하다      편안        0
3                            가볍고 상쾌하다      기쁨        1
4                             가볍고 상쾌한      기쁨        1
...                               ...     ...      ...
28906       대신에 끝나면 얼마든지 귀여워해 줘도 된단다.      행복        2
28907  대신에 시 시험 끝나면 얼마든지 귀여워해 줘도 된단다.      행복        2
28908        열심히 저 네! 할게요! 형님, 감사합니다!      행복        2
28909        네! 형님, 열심히 할게요! 저 감사합니다!      행복        2
28910        네! 감사합니다! 열심히 할게요! 형님, 저      행복        2

[28911 rows x 3 columns]

In [47]:
fdic.to_excel('./data/최종사전_증강(긍부정).xlsx', index=False)

In [46]:
fdic = fdic.dropna()
fdic

                                 word emotion  emo_num
0                           가능성이 늘어나다      만족        4
1                            가능성이 있다고      기쁨        1
2                                가능하다      편안        0
3                            가볍고 상쾌하다      기쁨        1
4                             가볍고 상쾌한      기쁨        1
...                               ...     ...      ...
28906       대신에 끝나면 얼마든지 귀여워해 줘도 된단다.      행복        2
28907  대신에 시 시험 끝나면 얼마든지 귀여워해 줘도 된단다.      행복        2
28908        열심히 저 네! 할게요! 형님, 감사합니다!      행복        2
28909        네! 형님, 열심히 할게요! 저 감사합니다!      행복        2
28910        네! 감사합니다! 열심히 할게요! 형님, 저      행복        2

[28905 rows x 3 columns]